#!/usr/bin/env bash

# Function to display usage
usage() {
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
}

# Check if number of parameters is less than 4
if [ "$#" -lt 4 ]; then
    usage
fi

# Assign parameters to variables
path_to_file=$1
ip_address=$2
username=$3
ssh_key=$4

# Transfer file using scp
scp -i "$ssh_key" -o StrictHostKeyChecking=no "$path_to_file" "$username@$ip_address":~/

# Check if scp command was successful
if [ $? -eq 0 ]; then
    echo "File transfer successful"
else
    echo "File transfer failed"
fi

