#!/usr/bin/env bash

# Install nginx and echo "Hello World" into index.html
sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html >/dev/null

# Define Nginx configuration
new_config="
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /usr/share/nginx/html;  # Corrected root directory
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    
    location / {
        try_files \$uri \$uri/ =404;
    }
    
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
"

# Write new configuration to default file
echo "$new_config" | sudo tee /etc/nginx/sites-available/default >/dev/null

# Restart nginx
sudo service nginx restart

