#!/usr/bin/env bash

# Update package lists
sudo apt-get update

# Install Nginx (assuming root privileges for now)
sudo apt-get install nginx -y

# New server configuration with permanent redirect
new_config="
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    # Redirect all requests to Youtube video
    rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
}
"

# Save the configuration to the default location
echo "$new_config" > /etc/nginx/sites-available/default

# Check Nginx service status and start/restart accordingly
if ! systemctl status nginx &> /dev/null; then
  systemctl start nginx
else
  systemctl restart nginx
fi

